### ISSUE TITLE
[BUG]No such file or directory: 'data_voc/VOCdevkit/VOC2007/ImageSets/Segmentation/trainval.txt'

### ISSUE THREAD

**Issue by Ever-Bright-V** [xzyun2011/finetune_segment_anything_tutorial#1]
使用了 VOC2007 datasets 缺少 trainval.txt

```
EPOCH: 100, Loss: 0.04418242536485195
(SAM) (base) everbright@everbright-desktop:~/CodesWorld/Codes/finetune_segment_anything_tutorial$ python3 finetune_sam_voc.py --w weights/sam_vit_b_01ec64.pth --type vit_b --data data_voc/VOCdevkit
Traceback (most recent call last):
  File "/home/everbright/CodesWorld/Codes/finetune_segment_anything_tutorial/finetune_sam_voc.py", line 219, in <module>
    main(opt)
  File "/home/everbright/CodesWorld/Codes/finetune_segment_anything_tutorial/finetune_sam_voc.py", line 30, in main
    dataset = CustomDataset(data_folder, txt_name="trainval.txt")  ##  VOC seg is too small, used val for training
  File "/home/everbright/CodesWorld/Codes/finetune_segment_anything_tutorial/utils/custom_dataset.py", line 12, in __init__
    with open(os.path.join(VOCdevkit_path, f"VOC2007/ImageSets/Segmentation/{txt_name}"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data_voc/VOCdevkit/VOC2007/ImageSets/Segmentation/trainval.txt'
```

**Comment by Ever-Bright-V** [comment]
提供的VOC数据集的百度云盘链接版本貌似不对，官网的试了没问题
